### ISSUE TITLE
Fix History Integration

### ISSUE THREAD

**Issue by M0isT09** [joemar25/SE_Prototype_1#22]
need to be fixed for grammar, fluency, rate score

**Comment by joemar25** [comment]
![1](https://user-images.githubusercontent.com/80235976/233253595-261a0ef6-43fb-4fe0-8e99-8b0043206c27.PNG)
![2](https://user-images.githubusercontent.com/80235976/233253600-0b61351d-4d19-4ac9-8771-b010cae5a877.PNG)
![3](https://user-images.githubusercontent.com/80235976/233253602-6b5ceedc-e725-44f2-bffe-5b5591d65ef5.PNG)
![4](https://user-images.githubusercontent.com/80235976/233253603-4c2236ef-4406-44c9-857c-408ea96fee7f.PNG)
![5](https://user-images.githubusercontent.com/80235976/233253606-9db64dd7-2f86-490e-9590-2dfd811282e0.PNG)
![6](https://user-images.githubusercontent.com/80235976/233253609-c493cbc1-6be3-49e8-ac1f-607caa79d277.PNG)
